//  IMPORTIAMO DATA/POSTS PERCHE ANDIAMO A SEPARARE LA LOGICA DAL FILE /ROUTERS/POSTS DOVE GESTIAMO LE DIVERSE RICHIESTE E LA AGGIUGIAMO QUI CON DELLE FUNZIONI CHE ANDREMO A RICHIAMARE IN ROUTER
const data = require("../data/posts");
